// 32x32 checker PNG bundled with the probe (no network).
export const LOGO_PNG_DATA_URL = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAOUlEQVR42mOQL9+CFV1T18CKSFXPMGrBqAVDwAJqGYRL/agFoxYMBQtGi4pRC0YtGK0PRi0YtQCIANjN3j1FY5c3AAAAAElFTkSuQmCC';
