using System.Text.Json;
using System.Text.Json.Nodes;
using Diagram.Core.Contracts;
using Xunit;

namespace Diagram.Contracts.Tests;

/// <summary>
/// Every shared DTO fixture produced by the TypeScript engine must deserialize into the
/// generated C# type and re-serialize to semantically identical JSON (no dropped,
/// renamed or defaulted fields; null versus absent preserved).
/// </summary>
public sealed class SchemaParityTests
{
    private static readonly string Root = FindRoot();

    private static string FindRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "contracts"))) dir = dir.Parent;
        return dir?.FullName ?? throw new DirectoryNotFoundException("contracts/");
    }

    public static TheoryData<string, Type> Fixtures => new()
    {
        { "document.json", typeof(DiagramDocument) },
        { "snapshot.json", typeof(Snapshot) },
        { "export-snapshot.json", typeof(ExportSnapshot) },
        { "operations.json", typeof(List<Operation>) },
        { "transaction-result.json", typeof(TransactionResult) },
        { "committed-event.json", typeof(CommittedEvent) },
        { "change-set.json", typeof(ChangeSet) },
        { "response-error.json", typeof(ResponseEnvelope) },
        { "response-result.json", typeof(ResponseEnvelope) },
        { "request-envelope.json", typeof(RequestEnvelope) },
        { "prepared-asset.json", typeof(PreparedAsset) },
        { "diagnostic.json", typeof(Diagnostic) },
    };

    [Theory]
    [MemberData(nameof(Fixtures))]
    public void FixtureRoundTripsExactly(string file, Type type)
    {
        var json = File.ReadAllText(Path.Combine(Root, "contracts", "fixtures", "parity", file));
        var value = JsonSerializer.Deserialize(json, type, ContractJson.Options);
        Assert.NotNull(value);
        var back = JsonSerializer.Serialize(value, type, ContractJson.Options);
        var expected = JsonNode.Parse(json);
        var actual = JsonNode.Parse(back);
        Assert.True(JsonNode.DeepEquals(expected, actual), $"{file} differs after C# round trip:\n{back}");
    }

    [Fact]
    public void ElementUnionUsesKindDiscriminator()
    {
        var doc = ContractJson.Deserialize<DiagramDocument>(File.ReadAllText(Path.Combine(Root, "contracts", "fixtures", "parity", "document.json")));
        var kinds = doc.Pages[0].Elements.Select(e => e.Kind()).Distinct().ToList();
        Assert.Contains("image", kinds);
        Assert.Contains("shape", kinds);
        Assert.Equal(20, doc.Pages[0].Elements.Count);
    }

    [Fact]
    public void UnknownFieldsAreRejected()
    {
        Assert.Throws<JsonException>(() => ContractJson.Deserialize<Bounds>("""{"x":1,"y":2,"width":3,"height":4,"depth":5}"""));
        Assert.Throws<JsonException>(() => ContractJson.Deserialize<List<Operation>>("""[{"op":"explode","target":"x"}]"""));
    }

    [Fact]
    public void NullVersusAbsentIsPreservedInPatches()
    {
        var ops = ContractJson.Deserialize<List<Operation>>("""[{"op":"set","target":"t","patch":{"alias":null,"name":"n"}}]""");
        var patch = ((SetOp)ops[0]).Patch;
        Assert.Equal(JsonValueKind.Null, patch.Alias.ValueKind);
        Assert.Equal(JsonValueKind.Undefined, patch.Text.ValueKind);
    }

    [Fact]
    public void GeneratedSourcesAreCurrent()
    {
        // The generator's --check mode is run by CI (npm); here we only assert the file exists and
        // was produced from the same bundle (header marker).
        var g = File.ReadAllText(Path.Combine(Root, "src", "Diagram.Core.Contracts", "Generated", "Contracts.g.cs"));
        Assert.StartsWith("// GENERATED by tools/generate-contracts.mjs", g);
    }
}
