// GENERATED by tools/generate-contracts.mjs from contracts/*.schema.json. Do not edit.
/* eslint-disable */

export type Uuid = string;

export type Alias = string;

export type AssetId = string;

export type Colour = string;

/** Solid colour or none. */
export type Paint = string;

export type Point = {
  x: number;
  y: number;
};

export type Bounds = {
  x: number;
  y: number;
  width: number;
  height: number;
};

export type Metadata = Record<string, string>;

export type Dash = "solid" | "dash" | "dot" | "dashDot";

export type Arrow = "none" | "triangle" | "open" | "diamond" | "circle";

export type TextBlock = {
  value: string;
  fontFamily: string;
  fontSizePt: number;
  bold: boolean;
  italic: boolean;
  underline: boolean;
  colour: Colour;
  horizontalAlign: "left" | "center" | "right";
  verticalAlign: "top" | "middle" | "bottom";
  wrap: boolean;
  paddingPt: number;
};

export type ShapeStyle = {
  fill: Paint;
  fillOpacity: number;
  stroke: Paint;
  strokeWidthPt: number;
  dash: Dash;
  lineCap: "butt" | "round" | "square";
  lineJoin: "miter" | "round" | "bevel";
};

export type LineStyle = {
  stroke: Colour;
  strokeWidthPt: number;
  dash: Dash;
  startArrow: Arrow;
  endArrow: Arrow;
};

/** Static connection point in element-local normalised coordinates (0..1), fixed under rotation. */
export type Port = {
  name: string;
  x: number;
  y: number;
};

export type Endpoint = {
  elementId?: Uuid;
  port?: string;
  point?: Point;
  glue: "dynamic" | "static" | "none";
};

export type Guide = {
  id: Uuid;
  orientation: "horizontal" | "vertical";
  positionPt: number;
};

export type Layer = {
  id: Uuid;
  name: string;
  visible: boolean;
  locked: boolean;
  printable: boolean;
  snap: boolean;
  glue: boolean;
  colourOverride?: Colour;
};

export type ElementCommon = {
  id: Uuid;
  alias?: Alias;
  name?: string;
  layerIds: Uuid[];
  zIndex: number;
  locked: boolean;
  hidden: boolean;
  bounds: Bounds;
  rotationDeg: number;
  metadata: Metadata;
};

export type ShapeGeometry = {
  preset?: "rectangle" | "roundedRect" | "ellipse" | "diamond" | "triangle" | "hexagon" | "parallelogram" | "cylinder" | "cloud" | "callout" | "server" | "database" | "application" | "user" | "document" | "custom";
  svgPath?: string;
  cornerRadiusPt?: number;
};

export type ShapeElement = {
  id: Uuid;
  alias?: Alias;
  name?: string;
  layerIds: Uuid[];
  zIndex: number;
  locked: boolean;
  hidden: boolean;
  bounds: Bounds;
  rotationDeg: number;
  metadata: Metadata;
  kind: "shape";
  geometry: ShapeGeometry;
  style: ShapeStyle;
  text?: TextBlock;
  ports?: Port[];
};

export type TextElement = {
  id: Uuid;
  alias?: Alias;
  name?: string;
  layerIds: Uuid[];
  zIndex: number;
  locked: boolean;
  hidden: boolean;
  bounds: Bounds;
  rotationDeg: number;
  metadata: Metadata;
  kind: "text";
  text: TextBlock;
  style: ShapeStyle;
};

export type ImageElement = {
  id: Uuid;
  alias?: Alias;
  name?: string;
  layerIds: Uuid[];
  zIndex: number;
  locked: boolean;
  hidden: boolean;
  bounds: Bounds;
  rotationDeg: number;
  metadata: Metadata;
  kind: "image";
  assetId: AssetId;
  fit: "contain" | "cover" | "stretch";
  opacity: number;
  preserveAspectRatio: boolean;
};

export type ConnectorElement = {
  id: Uuid;
  alias?: Alias;
  name?: string;
  layerIds: Uuid[];
  zIndex: number;
  locked: boolean;
  hidden: boolean;
  bounds: Bounds;
  rotationDeg: number;
  metadata: Metadata;
  kind: "connector";
  from: Endpoint;
  to: Endpoint;
  route: "straight" | "orthogonal" | "curved";
  waypoints: Point[];
  style: LineStyle;
  label?: TextBlock;
};

export type GroupElement = {
  id: Uuid;
  alias?: Alias;
  name?: string;
  layerIds: Uuid[];
  zIndex: number;
  locked: boolean;
  hidden: boolean;
  bounds: Bounds;
  rotationDeg: number;
  metadata: Metadata;
  kind: "group";
  childIds: Uuid[];
};

export type Element = ShapeElement | TextElement | ImageElement | ConnectorElement | GroupElement;

export type Page = {
  id: Uuid;
  name: string;
  widthPt: number;
  heightPt: number;
  background: Paint;
  grid: {
    visible: boolean;
    spacingPt: number;
    snap: boolean;
  };
  guides: Guide[];
  layers: Layer[];
  elements: Element[];
};

export type Asset = {
  id: AssetId;
  name: string;
  mimeType: "image/png" | "image/jpeg" | "image/bmp" | "image/svg+xml";
  sha256: string;
  widthPx?: number;
  heightPx?: number;
  sourcePath?: string;
  embeddedData?: string;
  tags: string[];
  provenance?: string;
};

export type DiagramDocument = {
  schemaVersion: 1;
  id: Uuid;
  title: string;
  revision: number;
  pages: Page[];
  assets: Asset[];
  metadata: Metadata;
  source?: {
    format: "vsdx" | "native-json";
    path?: string;
  };
};

/** UUID, page-scoped alias or exact display name (resolved in that order; names require batch pageId). */
export type Target = string;

export type Targets = Target[];

export type PointPt = {
  xPt: number;
  yPt: number;
};

export type BoundsPatch = {
  x?: number;
  y?: number;
  width?: number;
  height?: number;
};

export type TextPatch = {
  value?: string;
  fontFamily?: string;
  fontSizePt?: number;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  colour?: Colour;
  horizontalAlign?: "left" | "center" | "right";
  verticalAlign?: "top" | "middle" | "bottom";
  wrap?: boolean;
  paddingPt?: number;
};

/** Shape style leaves (shape/text) or line style leaves (connector); kind-specific validity is checked by the planner. */
export type StylePatch = {
  fill?: Paint;
  fillOpacity?: number;
  stroke?: Paint;
  strokeWidthPt?: number;
  dash?: Dash;
  lineCap?: "butt" | "round" | "square";
  lineJoin?: "miter" | "round" | "bevel";
  startArrow?: Arrow;
  endArrow?: Arrow;
};

/** Nested leaf patch. Omission preserves; null clears a nullable property; arrays replace atomically. id/kind are immutable. */
export type ElementPatch = {
  alias?: Alias | null;
  name?: string | null;
  locked?: boolean;
  hidden?: boolean;
  metadata?: Record<string, string | null>;
  bounds?: BoundsPatch;
  rotationDeg?: number;
  style?: StylePatch;
  text?: TextPatch | null;
  label?: TextPatch | null;
  geometry?: ShapeGeometry;
  ports?: Port[];
  assetId?: AssetId;
  fit?: "contain" | "cover" | "stretch";
  opacity?: number;
  preserveAspectRatio?: boolean;
  from?: EndpointInput;
  to?: EndpointInput;
  route?: "straight" | "orthogonal" | "curved";
  waypoints?: Point[];
};

/** Endpoint whose element may be a target string (resolved to a UUID before commit). */
export type EndpointInput = {
  target?: Target;
  port?: string;
  point?: Point;
  glue?: "dynamic" | "static" | "none";
};

/** New element. Omitted fields take engine defaults; id is engine-generated unless supplied. */
export type ElementInput = {
  kind: "shape" | "text" | "image" | "connector";
  id?: Uuid;
  alias?: Alias;
  name?: string;
  layerIds?: string[];
  locked?: boolean;
  hidden?: boolean;
  metadata?: Metadata;
  bounds?: Bounds;
  rotationDeg?: number;
  style?: StylePatch;
  text?: TextPatch;
  label?: TextPatch;
  geometry?: ShapeGeometry;
  ports?: Port[];
  assetId?: AssetId;
  fit?: "contain" | "cover" | "stretch";
  opacity?: number;
  preserveAspectRatio?: boolean;
  from?: EndpointInput;
  to?: EndpointInput;
  route?: "straight" | "orthogonal" | "curved";
  waypoints?: Point[];
};

export type PageInput = {
  id?: Uuid;
  name?: string;
  widthPt?: number;
  heightPt?: number;
  background?: Paint;
  grid?: {
    visible?: boolean;
    spacingPt?: number;
    snap?: boolean;
  };
  guides?: Guide[];
};

export type LayerInput = {
  id?: Uuid;
  name?: string;
  visible?: boolean;
  locked?: boolean;
  printable?: boolean;
  snap?: boolean;
  glue?: boolean;
  colourOverride?: Colour | null;
};

export type CreateOp = {
  op: "create";
  pageId?: string;
  element: ElementInput;
};

export type SetOp = {
  op: "set";
  target: Target;
  patch: ElementPatch;
};

/** Exactly one of to (absolute top-left) or delta. */
export type MoveOp = {
  op: "move";
  target: Target;
  to?: PointPt;
  delta?: PointPt;
};

export type ResizeOp = {
  op: "resize";
  target: Target;
  widthPt?: number;
  heightPt?: number;
};

/** angleDeg (absolute; shape/text/image) xor deltaDeg (relative; any). pivot only for groups. */
export type RotateOp = {
  op: "rotate";
  target: Target;
  angleDeg?: number;
  deltaDeg?: number;
  pivot?: PointPt;
};

export type DeleteOp = {
  op: "delete";
  target: Target;
  connectors?: "reject" | "detach" | "delete";
  subtree?: boolean;
};

export type DuplicateOp = {
  op: "duplicate";
  targets: Targets;
  offset?: PointPt;
  aliases?: Record<string, Alias>;
  ids?: Record<string, Uuid>;
};

export type GroupOp = {
  op: "group";
  targets: Targets;
  id?: Uuid;
  alias?: Alias;
  name?: string;
};

export type UngroupOp = {
  op: "ungroup";
  target: Target;
};

export type AlignOp = {
  op: "align";
  targets: Targets;
  edge: "left" | "center" | "right" | "top" | "middle" | "bottom";
};

export type DistributeOp = {
  op: "distribute";
  targets: Targets;
  axis: "horizontal" | "vertical";
};

export type SetGapOp = {
  op: "setGap";
  targets: Targets;
  axis: "horizontal" | "vertical";
  gapPt: number;
};

export type ZOrderOp = {
  op: "zorder";
  targets: Targets;
  action: "front" | "back" | "forward" | "backward";
};

export type AddPageOp = {
  op: "addPage";
  page?: PageInput;
  index?: number;
};

export type SetPageOp = {
  op: "setPage";
  pageId: string;
  patch: PageInput;
};

export type ReorderPageOp = {
  op: "reorderPage";
  pageId: string;
  index: number;
};

export type DuplicatePageOp = {
  op: "duplicatePage";
  pageId: string;
  newPageId?: Uuid;
  name?: string;
};

export type DeletePageOp = {
  op: "deletePage";
  pageId: string;
};

export type AddLayerOp = {
  op: "addLayer";
  pageId?: string;
  layer: LayerInput;
};

export type SetLayerOp = {
  op: "setLayer";
  pageId?: string;
  layer: string;
  patch: LayerInput;
};

export type AssignLayerOp = {
  op: "assignLayer";
  targets: Targets;
  layers: string[];
  mode?: "set" | "add" | "remove";
};

export type DeleteLayerOp = {
  op: "deleteLayer";
  pageId?: string;
  layer: string;
};

/** Registers a host-prepared asset descriptor (bytes already durable in the host blob store). */
export type RegisterAssetOp = {
  op: "registerAsset";
  asset: Asset;
};

export type SetAssetOp = {
  op: "setAsset";
  assetId: AssetId;
  patch: {
    name?: string;
    tags?: string[];
  };
};

/** Explicit document-global replacement: every image referencing from now references to. */
export type ReplaceAssetGlobalOp = {
  op: "replaceAssetGlobal";
  fromAssetId: AssetId;
  toAssetId: AssetId;
};

export type DeleteAssetOp = {
  op: "deleteAsset";
  assetId: AssetId;
};

export type Operation = CreateOp | SetOp | MoveOp | ResizeOp | RotateOp | DeleteOp | DuplicateOp | GroupOp | UngroupOp | AlignOp | DistributeOp | SetGapOp | ZOrderOp | AddPageOp | SetPageOp | ReorderPageOp | DuplicatePageOp | DeletePageOp | AddLayerOp | SetLayerOp | AssignLayerOp | DeleteLayerOp | RegisterAssetOp | SetAssetOp | ReplaceAssetGlobalOp | DeleteAssetOp;

export type OperationBatch = Operation[];

export type Scope = {
  documentId: Uuid;
  sessionId: Uuid;
  pageId?: string;
};

export type MutationRequest = {
  documentId: Uuid;
  sessionId: Uuid;
  pageId?: string;
  transactionId: Uuid;
  baseRevision: number;
  atomic?: true;
  description?: string;
  operations: OperationBatch;
};

/** Host-issued opaque capability for approved bytes; never a filesystem path. */
export type PreparedAssetRef = {
  preparationId: string;
  asset: Asset;
  expiresAt: string;
};

export type PreparedAsset = {
  ref: PreparedAssetRef;
  byteLength: number;
  sanitised?: boolean;
};

export type ScriptRequest = {
  documentId: Uuid;
  sessionId: Uuid;
  pageId?: string;
  transactionId: Uuid;
  baseRevision: number;
  atomic?: true;
  script: string;
  preparedAssetRefs?: Record<string, PreparedAssetRef>;
};

export type UndoRequest = {
  documentId: Uuid;
  sessionId: Uuid;
  transactionId: Uuid;
  baseRevision: number;
};

export type Diagnostic = {
  severity: "info" | "warning" | "error";
  code: string;
  pageId?: string;
  sourceShapeId?: string;
  elementId?: string;
  action?: "preserved" | "approximated" | "dropped" | "regenerated";
  detail: string;
};

export type ErrorCode = "not_running" | "not_ready" | "no_document" | "session_mismatch" | "document_mismatch" | "unsupported_version" | "invalid_request" | "not_found" | "ambiguous_target" | "revision_conflict" | "locked_target" | "limit_exceeded" | "history_unavailable" | "transaction_id_conflict" | "timeout_unknown" | "io_error" | "compatibility_loss" | "projection_failed" | "busy" | "busy_user_editing" | "path_not_permitted" | "consent_denied" | "dependency_conflict" | "method_not_found" | "checkpoint_required" | "internal_error";

export type AppError = {
  code: ErrorCode;
  message: string;
  retryable: boolean;
  outcome?: "not_applied" | "unknown";
  details?: Record<string, unknown>;
};

export type TransactionResult = {
  transactionId: string;
  previousRevision: number;
  revision: number;
  noChange: boolean;
  created: string[];
  changed: string[];
  deleted: string[];
  changedPageIds: string[];
  changedLayerIds: string[];
  changedAssetIds: string[];
  visuallyAffectedIds: string[];
  warnings: Diagnostic[];
  projectionStatus: "applied" | "failed";
  aliases?: Record<string, string>;
  operations?: Operation[];
};

/** Resolved change of one entity. before/after are full canonical values (null = absent). Deterministic: replay never generates IDs. */
export type EntityChange = {
  entity: "document" | "page" | "element" | "asset";
  id: string;
  pageId?: string;
  before: Record<string, unknown> | null;
  after: Record<string, unknown> | null;
};

export type ResolvedDiff = {
  source: "gui" | "script" | "mcp" | "import" | "undo" | "redo";
  transactionId: string;
  previousRevision: number;
  revision: number;
  changes: EntityChange[];
};

export type CommittedEvent = {
  sequence: number;
  documentId: string;
  sessionId: string;
  revision: number;
  resolvedDiff: ResolvedDiff;
};

export type TransactionSummary = {
  transactionId: string;
  source: "gui" | "script" | "mcp" | "import" | "undo" | "redo";
  revision: number;
  description: string;
  created: string[];
  changed: string[];
  deleted: string[];
  nonElementChanges: string[];
  timestamp: string;
};

export type ChangeSet = {
  documentId: string;
  sessionId: string;
  revision: number;
  earliestRetainedRevision: number;
  transactions: TransactionSummary[];
};

export type Snapshot = {
  documentId: string;
  sessionId: string;
  pageId?: string;
  revision: number;
  document: DiagramDocument;
};

export type ConnectorProjection = {
  routePoints: Point[];
  visualBounds: Bounds;
};

/** Non-canonical derived sidecar computed from one committed snapshot. */
export type Projection = {
  documentId: string;
  sessionId: string;
  pageId?: string;
  revision: number;
  connectors: Record<string, ConnectorProjection>;
  groupVisualBounds: Record<string, Bounds>;
};

export type ExportSnapshot = {
  documentId: string;
  sessionId: string;
  pageId?: string;
  revision: number;
  document: DiagramDocument;
  projection: Projection;
};

/** Host-stamped telemetry; caller-supplied values are discarded; never an idempotency key. */
export type Origin = {
  source: "gui" | "mcp" | "host";
  clientLabel?: string;
  connectionId?: string;
};

export type RequestEnvelope = {
  protocolVersion: 1;
  kind: "request";
  requestId: string;
  method: string;
  documentId?: Uuid;
  sessionId?: Uuid;
  deadlineMs?: number;
  origin?: Origin;
  params: Record<string, unknown>;
};

export type ResponseEnvelope = {
  protocolVersion: 1;
  kind: "response";
  requestId: string;
  documentId?: string;
  sessionId?: string;
  result?: unknown;
  error?: AppError;
};

export type EventEnvelope = {
  protocolVersion: 1;
  kind: "event";
  method: "editor.ready" | "doc.opened" | "doc.closed" | "doc.committed" | "doc.dirtyChanged" | "editor.gesture";
  sequence: number;
  documentId?: string;
  sessionId?: string;
  revision?: number;
  payload: Record<string, unknown>;
};

