using System.ComponentModel;
using System.Text.Json;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace Diagram.Mcp;

/// <summary>
/// Source §11.2 tool surface. Mutation tools require the document/session identity returned by
/// reads plus a caller-generated transactionId (UUID) and baseRevision; the shim adds nothing.
/// Retrying with the same transactionId after an unknown outcome returns the original result.
/// </summary>
[McpServerToolType]
public sealed class DiagramTools(ShimConnection pipe)
{
    private async Task<(string? Doc, string? Session, CallToolResult? Error)> ScopeAsync(string? documentId, string? sessionId, CancellationToken ct)
    {
        if (documentId is not null && sessionId is not null) return (documentId, sessionId, null);
        if (documentId is not null || sessionId is not null) return (null, null, ToolResults.Invalid("give both documentId and sessionId, or neither for the current document"));
        var cur = await pipe.CallAsync("app.current", null, null, new { }, ct);
        if (cur.Error is not null) return (null, null, ToolResults.From(cur));
        return (cur.Result.GetProperty("documentId").GetString(), cur.Result.GetProperty("sessionId").GetString(), null);
    }

    [McpServerTool(Name = "get_document_summary", ReadOnly = true), Description("Compact semantic summary: document/session IDs and revision, pages, layers, elements (ID, alias, name, type, bounds, text, connections) and referenced asset IDs. Call this first; use the returned documentId/sessionId/revision for edits.")]
    public async Task<CallToolResult> GetDocumentSummary(
        [Description("Restrict to one page (ID or name)")] string? pageId = null,
        [Description("Include bounds (default true)")] bool includeGeometry = true,
        [Description("Include styles (default false)")] bool includeStyle = false,
        [Description("Include hidden elements (default false)")] bool includeHidden = false,
        [Description("Document UUID (omit with sessionId for the current document)")] string? documentId = null,
        [Description("Session UUID")] string? sessionId = null,
        CancellationToken ct = default)
    {
        var (d, s, e) = await ScopeAsync(documentId, sessionId, ct);
        if (e is not null) return e;
        return ToolResults.From(await pipe.CallAsync("doc.summary", d, s, new { pageId, includeGeometry, includeStyle, includeHidden }, ct));
    }

    [McpServerTool(Name = "get_objects", ReadOnly = true), Description("Complete canonical objects for the given element UUIDs.")]
    public async Task<CallToolResult> GetObjects(
        [Description("Element UUIDs")] string[] ids,
        string? documentId = null, string? sessionId = null, CancellationToken ct = default)
    {
        var (d, s, e) = await ScopeAsync(documentId, sessionId, ct);
        if (e is not null) return e;
        return ToolResults.From(await pipe.CallAsync("doc.getObjects", d, s, new { ids }, ct));
    }

    [McpServerTool(Name = "apply_operations", Destructive = true), Description("Canonical mutation tool: one atomic batch of typed operations (create, set, move, resize, rotate, delete, duplicate, group, ungroup, align, distribute, setGap, zorder, page/layer/asset operations). Only the targeted objects change. Returns previous/current revision and created/changed/deleted IDs. On revision_conflict, re-read with get_changes. After an unknown outcome, retry with the SAME transactionId.")]
    public async Task<CallToolResult> ApplyOperations(
        [Description("Document UUID from a read")] string documentId,
        [Description("Session UUID from a read")] string sessionId,
        [Description("Caller-generated UUID identifying this batch; reuse it only to retry the identical batch")] string transactionId,
        [Description("Revision the batch was planned against")] long baseRevision,
        [Description("Operation array (see contracts/operations.schema.json)")] JsonElement operations,
        [Description("Page for alias/name targets")] string? pageId = null,
        [Description("Must be true or omitted; partial execution is not supported")] bool atomic = true,
        [Description("Short human-readable description for the transaction log")] string? description = null,
        CancellationToken ct = default)
    {
        if (!atomic) return ToolResults.Invalid("atomic:false is not supported");
        if (!Guid.TryParse(transactionId, out _)) return ToolResults.Invalid("transactionId must be a UUID generated by the caller");
        return ToolResults.From(await pipe.CallAsync("doc.apply", documentId, sessionId, new { pageId, transactionId, baseRevision, atomic = true, operations, description }, ct));
    }

    [McpServerTool(Name = "execute_script", Destructive = true), Description("Compile DrawScript and execute it as one atomic transaction. Returns the compiled operations and the transaction result.")]
    public async Task<CallToolResult> ExecuteScript(
        string documentId, string sessionId,
        [Description("Caller-generated UUID; reuse only to retry the identical script")] string transactionId,
        long baseRevision,
        [Description("DrawScript source (see docs/drawscript.md)")] string script,
        string? pageId = null, bool atomic = true, CancellationToken ct = default)
    {
        if (!atomic) return ToolResults.Invalid("atomic:false is not supported");
        if (!Guid.TryParse(transactionId, out _)) return ToolResults.Invalid("transactionId must be a UUID generated by the caller");
        return ToolResults.From(await pipe.CallAsync("doc.executeScript", documentId, sessionId, new { pageId, transactionId, baseRevision, atomic = true, script }, ct));
    }

    [McpServerTool(Name = "render_page", ReadOnly = true), Description("Render a page to PNG/JPEG labelled with the revision it shows. mode=debug overlays IDs/aliases and bounds.")]
    public async Task<CallToolResult> RenderPage(
        string pageId, string format = "png", int maxWidth = 1600, int maxHeight = 1200, string mode = "clean",
        string? documentId = null, string? sessionId = null, CancellationToken ct = default)
    {
        var (d, s, e) = await ScopeAsync(documentId, sessionId, ct);
        if (e is not null) return e;
        return ToolResults.Image(await pipe.CallAsync("doc.render", d, s, new { pageId, format, maxWidth, maxHeight, mode }, ct));
    }

    [McpServerTool(Name = "render_region", ReadOnly = true), Description("Render part of a page: exactly one of bounds (pt) or elementIds, plus padding.")]
    public async Task<CallToolResult> RenderRegion(
        string pageId,
        [Description("Region in points: {x,y,width,height}")] JsonElement? bounds = null,
        [Description("Elements whose visual bounds define the region")] string[]? elementIds = null,
        double paddingPt = 12, string format = "png", int maxWidth = 1600, int maxHeight = 1200, string mode = "clean",
        string? documentId = null, string? sessionId = null, CancellationToken ct = default)
    {
        if ((bounds is null) == (elementIds is null)) return ToolResults.Invalid("give exactly one of bounds or elementIds");
        var (d, s, e) = await ScopeAsync(documentId, sessionId, ct);
        if (e is not null) return e;
        return ToolResults.Image(await pipe.CallAsync("doc.render", d, s, new { pageId, region = new { bounds, elementIds, paddingPt }, format, maxWidth, maxHeight, mode }, ct));
    }

    [McpServerTool(Name = "inspect_layout", ReadOnly = true), Description("Machine-readable layout warnings (outside page, overlaps, text overflow, dangling connectors, image distortion, low contrast…) with element IDs and bounds.")]
    public async Task<CallToolResult> InspectLayout(string? pageId = null, string? documentId = null, string? sessionId = null, CancellationToken ct = default)
    {
        var (d, s, e) = await ScopeAsync(documentId, sessionId, ct);
        if (e is not null) return e;
        return ToolResults.From(await pipe.CallAsync("doc.inspectLayout", d, s, new { pageId }, ct));
    }

    [McpServerTool(Name = "list_assets", ReadOnly = true), Description("Approved assets (document and per-user library) with IDs, names, MIME types, dimensions, tags, scope and version. Prefer these IDs over searching for logos.")]
    public async Task<CallToolResult> ListAssets(string? query = null, string[]? tags = null, CancellationToken ct = default)
    {
        var (d, s, e) = await ScopeAsync(null, null, ct);
        if (e is not null) return e;
        return ToolResults.From(await pipe.CallAsync("assets.list", d, s, new { query, tags }, ct));
    }

    [McpServerTool(Name = "get_changes", ReadOnly = true), Description("Transaction summaries since a revision (transactionId, source, created/changed/deleted IDs). Use after revision_conflict or an unknown outcome.")]
    public async Task<CallToolResult> GetChanges(string documentId, string sessionId, long sinceRevision, CancellationToken ct = default) =>
        ToolResults.From(await pipe.CallAsync("doc.getChanges", documentId, sessionId, new { sinceRevision }, ct));

    [McpServerTool(Name = "export_document", Destructive = false), Description("Export to vsdx|svg|png|jpeg. Without a path the app writes to the open document's folder or its export workspace; other locations need the user's approval in the app.")]
    public async Task<CallToolResult> ExportDocument(string format, string documentId, string sessionId, string? path = null, CancellationToken ct = default)
    {
        if (format is not ("vsdx" or "svg" or "png" or "jpeg")) return ToolResults.Invalid("format must be vsdx, svg, png or jpeg");
        return ToolResults.From(await pipe.CallAsync("doc.export", documentId, sessionId, new { format, path }, ct));
    }
}
